/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KIT_Einheiten_JNI_JNIMain */

#ifndef _Included_KIT_Einheiten_JNI_JNIMain
#define _Included_KIT_Einheiten_JNI_JNIMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KIT_Einheiten_JNI_JNIMain
 * Method:    sagHallo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_KIT_1Einheiten_JNI_JNIMain_sagHallo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
